version: 2
updates:
  - package-ecosystem: "npm" # 查看 GitHub 文档以了解其他支持的包生态系统
    directory: "/" # 在哪个目录下运行 Dependabot
    schedule:
      interval: "weekly" # 更新频率，可选项包括 "daily", "weekly", "monthly"
    open-pull-requests-limit: 10 # 同时打开的 PR 数量限制
